export const TAB_DASHBOARD_ITEM_CHANGED = "TAB_DASHBOARD_ITEM_CHANGED"
export const TAB_DASHBOARD_MENU_CHANGED = "TAB_DASHBOARD_MENU_CHANGED"
export const HOME_PAGE_SCROLL = "HOME_PAGE_SCROLL"
export const COLLAPSE_DASHBOARD = "COLLAPSE_DASHBOARD";
